das.named: simplify
The code was rejected (invalid call to super class constructor) by
Clang 4.  But it turns out it can simplified: let DefaultFor swap its
template parameters, so that we can swap them and have the second
inferred from the first.

But that's not yet enough to please clang 4 (see below).

Most of the diffs comes from the fact that I moved blocks of code.

In file included from tests/elle/das/cli.cc:1:
In file included from src/elle/das/cli.hh:21:
src/elle/das/named.hh:122:13: error: no matching constructor for initialization of 'DefaultFor<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]> >'
          : DefaultFor<Formal>(std::forward<Args>(args))...
            ^                  ~~~~~~~~~~~~~~~~~~~~~~~~
src/elle/das/named.hh:368:17: note: in instantiation of function template specialization 'elle::das::named::DefaultStore<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>,
      elle::das::SS<Symbol_baz>::Effective<int, int &&, int> >::DefaultStore<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>, elle::das::SS<Symbol_baz>::Effective<int, int &&, int> >'
      requested here
        return {DefaultStore<Args...>(std::forward<Args>(args)...)};
                ^
tests/elle/das/cli.cc:263:40: note: in instantiation of function template specialization 'elle::das::named::prototype<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>,
      elle::das::SS<Symbol_baz>::Effective<int, int &&, int> >' requested here
  auto const proto = elle::das::named::prototype(foo = "16", baz = 42);
                                       ^
src/elle/das/Symbol.hh:100:9: note: candidate inherited constructor not viable: no known conversion from 'elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>' to 'char const[3]' for
      1st argument
        Effective(Passing v)
        ^
src/elle/das/named.hh:113:22: note: constructor from base class 'Effective<char const (&)[3], char const (&)[3], char const (&)[3]>' inherited here
        using Super::Super;
                     ^
src/elle/das/named.hh:93:14: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>' to
      'const elle::das::named::DefaultFor<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>, true>' for 1st argument
      struct DefaultFor;
             ^
src/elle/das/named.hh:93:14: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>' to
      'elle::das::named::DefaultFor<elle::das::SS<Symbol_foo>::Effective<char const (&)[3], char const (&)[3], char const (&)[3]>, true>' for 1st argument
      struct DefaultFor;
             ^
src/elle/das/Symbol.hh:92:9: note: candidate template ignored: inherited constructor cannot be used to move object
        Effective(Effective<OE, OP>&& e)
        ^
src/elle/das/named.hh:113:22: note: constructor from base class 'Effective<char const (&)[3], char const (&)[3], char const (&)[3]>' inherited here
        using Super::Super;
                     ^
src/elle/das/named.hh:93:14: note: candidate constructor (the implicit default constructor) not viable: requires 0 arguments, but 1 was provided
      struct DefaultFor;
             ^